### ISSUE TITLE
Cool project! How well does this work?

### ISSUE THREAD

**Issue by ViktorNova** [Omega9/Reaper-test#2]
I have wanted to do this same thing with a private git repo like Gogs, how well does this work in your experience?

**Comment by Omega9** [comment]
I've barely tested it. Working with Git on Windows for a friend of mine, who agreed to help and participate, was a bit confusing.

Reaper's .rpp's are human-readable and ok for CVS. I wish someday it will be possible to push/pull or making branches from inside of Reaper just by clicking a button on a panel. I don't know if reaper's scripts are capable to do such things.

**Comment by ViktorNova** [comment]
I would love that too, my band and I have been talking about such a feature. Thanks for responding!
